# Site settings
title: Tornados México
email: tornados@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: tornadosmexico
github_username: franciscoleoncrz

# Build settings
markdown: kramdown

theme: jekyll-theme-minimal
